parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"/HkA":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=a;var e=require("react");const t={};function a(a){const[s,n]=(0,e.useState)([]),[o,r]=(0,e.useState)("unloaded");return(0,e.useEffect)(()=>{a?t[a]?n(t[a]):async function(){n([]),r("loading");const e=await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${a}`),s=await e.json();t[a]=s.breeds||[],n(t[a]),r("loaded")}():n([])},[a]),[s,o]}
},{}],"qepC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=t(require("react")),r=require("react-router-dom"),s=require("react/jsx-runtime");function t(e){return e&&e.__esModule?e:{default:e}}const i=({name:e,animal:t,breed:i,images:a,location:n,id:d})=>{let l="http://pets-images.dev-apis.com/pets/none.jpg";return a.length&&(l=a[0]),(0,s.jsxs)(r.Link,{id:d,to:`/details/${d}`,className:"pet",children:[(0,s.jsx)("div",{className:"image-container",children:(0,s.jsx)("img",{src:l,alt:e})}),(0,s.jsxs)("div",{className:"info",children:[(0,s.jsx)("h1",{children:e}),(0,s.jsxs)("h2",{children:[t," - ",i," - ",n]})]})]})};var a=i;exports.default=a;
},{}],"r5l1":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=a(require("./Pet")),t=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}const r=({pets:a})=>(0,t.jsx)("div",{className:"search",children:a.length?a.map(a=>(0,t.jsx)(e.default,{animal:a.animal,name:a.name,breed:a.breed,images:a.images,location:`${a.city}, ${a.state}`,id:a.id},a.id)):(0,t.jsx)("h2",{children:"No pets found"})});var s=r;exports.default=s;
},{"./Pet":"qepC"}],"2tnM":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react");const t=(0,e.createContext)(["green",()=>{}]);var r=t;exports.default=r;
},{}],"n0tu":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=n(require("./useBreedList")),a=n(require("./Results")),l=n(require("./ThemeContext")),r=require("react/jsx-runtime");function n(e){return e&&e.__esModule?e:{default:e}}const s=["bird","cat","dog","rabbit","reptile"],o=()=>{const[n,o]=(0,e.useState)(""),[i,u]=(0,e.useState)(""),[d,c]=(0,e.useState)(""),[h,x]=(0,e.useState)([]),[p]=(0,t.default)(n),[v,j]=(0,e.useContext)(l.default);async function m(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?animal=${n}&breed=${i}&location=${d}`),t=await e.json();x(t.pets)}return(0,e.useEffect)(()=>{m()},[]),(0,r.jsxs)("div",{className:"search-params",children:[(0,r.jsxs)("form",{onSubmit:e=>{e.preventDefault(),m()},children:[(0,r.jsxs)("label",{htmlFor:"location",children:["Location",(0,r.jsx)("input",{id:"location",value:d,placeholder:"Location",onChange:e=>c(e.target.value)})]}),(0,r.jsxs)("label",{htmlFor:"animal",children:["Animal",(0,r.jsxs)("select",{id:"animal",value:n,onChange:e=>o(e.target.value),onBlur:e=>o(e.target.value),children:[(0,r.jsx)("option",{}),s.map(e=>(0,r.jsx)("option",{value:e,children:e},e))]})]}),(0,r.jsxs)("label",{htmlFor:"breed",children:["Breed",(0,r.jsxs)("select",{disabled:!p.length,id:"breed",value:i,onChange:e=>u(e.target.value),onBlur:e=>u(e.target.value),children:[(0,r.jsx)("option",{}),p.map(e=>(0,r.jsx)("option",{value:e,children:e},e))]})]}),(0,r.jsxs)("label",{htmlFor:"theme",children:["Theme",(0,r.jsxs)("select",{value:v,onChange:e=>j(e.target.value),onBlur:e=>j(e.target.value),children:[(0,r.jsx)("option",{value:"darkblue",children:"Blue"}),(0,r.jsx)("option",{value:"darkgreen",children:"Green"}),(0,r.jsx)("option",{value:"darkred",children:"Red"}),(0,r.jsx)("option",{value:"darkorange",children:"Orange"})]})]}),(0,r.jsx)("button",{style:{backgroundColor:v},children:"Submit"})]}),(0,r.jsx)(a.default,{pets:h})]})};var i=o;exports.default=i;
},{"./useBreedList":"/HkA","./Results":"r5l1","./ThemeContext":"2tnM"}],"Ztkr":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),t=require("react/jsx-runtime");function a(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}class s extends e.Component{constructor(...e){super(...e),a(this,"state",{active:0})}handleIndexClick(e){this.setState({active:Number(e.target.dataset.index)})}render(){const{active:e}=this.state,{images:a}=this.props;return(0,t.jsxs)("div",{className:"carousel",children:[(0,t.jsx)("img",{src:a[e],alt:"animal"}),(0,t.jsx)("div",{className:"carousel-smaller",children:a.map((a,s)=>(0,t.jsx)("img",{src:a,className:s===e?"active":"",alt:"animal-thumbnail","data-index":s,onClick:e=>this.handleIndexClick(e)},a))})]})}}a(s,"defaultProps",{images:["http://pets-images.dev-apis.com/pets/none.jpg"]});var r=s;exports.default=r;
},{}],"mD05":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var r=require("react"),e=require("react-router-dom"),t=require("react/jsx-runtime");function o(r,e,t){return e in r?Object.defineProperty(r,e,{value:t,enumerable:!0,configurable:!0,writable:!0}):r[e]=t,r}class s extends r.Component{constructor(...r){super(...r),o(this,"state",{hasError:!1})}static getDerivedStateFromError(){return{hasError:!0,redirect:!1}}componentDidCatch(r,e){console.error("ErrorBoundary caught an error",{error:r,errorInfo:e}),setTimeout(()=>this.setState({redirect:!0}),5e3)}render(){return this.state.redirect?(0,t.jsx)(e.Redirect,{to:"/"}):this.state.hasError?(0,t.jsxs)("h2",{children:["This listing has an error.",(0,t.jsx)(e.Link,{to:"/",children:"Go back to the home page"}),", or wait to be redirected."]}):this.props.children}}var i=s;exports.default=i;
},{}],"KnKP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-dom"),t=require("react/jsx-runtime");let u;const c=({children:c})=>{u=u||document.getElementById("modal");const n=(0,e.useRef)(null);return n.current||(n.current=document.createElement("div")),(0,e.useEffect)(()=>(u.appendChild(n.current),()=>u.removeChild(n.current)),[]),(0,r.createPortal)((0,t.jsx)("div",{children:c}),n.current)};var n=c;exports.default=n;
},{}],"C/Dc":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=p;var e=require("react"),t=require("react-router-dom"),r=a(require("./Carousel")),o=a(require("./ErrorBoundary")),n=a(require("./ThemeContext")),s=a(require("./Modal")),i=require("react/jsx-runtime");function a(e){return e&&e.__esModule?e:{default:e}}function c(e,t){var r=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter(function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable})),r.push.apply(r,o)}return r}function l(e){for(var t=1;t<arguments.length;t++){var r=null!=arguments[t]?arguments[t]:{};t%2?c(Object(r),!0).forEach(function(t){d(e,t,r[t])}):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(r)):c(Object(r)).forEach(function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(r,t))})}return e}function d(e,t,r){return t in e?Object.defineProperty(e,t,{value:r,enumerable:!0,configurable:!0,writable:!0}):e[t]=r,e}class u extends e.Component{constructor(...e){super(...e),d(this,"state",{loading:!0,showModal:!1})}async componentDidMount(){const e=await fetch(`http://pets-v2.dev-apis.com/pets?id=${this.props.match.params.id}`),t=await e.json();this.setState(Object.assign({loading:!1},t.pets[0]))}toggleModal(){this.setState({showModal:!this.state.showModal})}adopt(){window.location="http://bit.ly/pet-adopt"}render(){if(this.state.loading)return(0,i.jsx)("h2",{style:{textAlign:"center"},children:"Loading..."});const{animal:e,breed:t,city:o,state:a,description:c,name:l,images:d,showModal:u}=this.state;return(0,i.jsxs)("div",{className:"details",children:[(0,i.jsx)(r.default,{images:d}),(0,i.jsxs)("div",{children:[(0,i.jsx)("h1",{children:l}),(0,i.jsxs)("h2",{children:[e," - ",t," - ",o,", ",a]}),(0,i.jsx)(n.default.Consumer,{children:([e])=>(0,i.jsxs)("button",{style:{backgroundColor:e},onClick:()=>this.toggleModal(),children:["Adopt ",l]})}),(0,i.jsx)("p",{children:c}),u?(0,i.jsx)(s.default,{children:(0,i.jsxs)("div",{children:[(0,i.jsxs)("h2",{children:["Would you like to adopt ",l,"?"]}),(0,i.jsxs)("div",{className:"buttons",children:[(0,i.jsx)("button",{onClick:()=>this.adopt(),children:"Adopt"}),(0,i.jsx)("button",{onClick:()=>this.toggleModal(),children:"Cancel"})]})]})}):null]})]})}}const h=(0,t.withRouter)(u);function p(e){return(0,i.jsx)(o.default,{children:(0,i.jsx)(h,l({},e))})}
},{"./Carousel":"Ztkr","./ErrorBoundary":"mD05","./ThemeContext":"2tnM","./Modal":"KnKP"}],"eBcb":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.default=void 0;var e=require("react"),r=require("react-router-dom"),t=u(require("./SearchParams")),d=u(require("./Details")),i=u(require("./ThemeContext")),s=require("react/jsx-runtime");function u(e){return e&&e.__esModule?e:{default:e}}const a=()=>{const u=(0,e.useState)("darkgreen");return(0,s.jsx)(e.StrictMode,{children:(0,s.jsx)(i.default.Provider,{value:u,children:(0,s.jsxs)("div",{children:[(0,s.jsx)("header",{children:(0,s.jsx)(r.Link,{to:"/",children:(0,s.jsx)("h1",{children:"Adopt Me!"})})}),(0,s.jsxs)(r.Switch,{children:[(0,s.jsx)(r.Route,{path:"/details/:id",children:(0,s.jsx)(d.default,{})}),(0,s.jsx)(r.Route,{path:"/",children:(0,s.jsx)(t.default,{})})]})]})})})};var l=a;exports.default=l;
},{"./SearchParams":"n0tu","./Details":"C/Dc","./ThemeContext":"2tnM"}],"Focm":[function(require,module,exports) {
"use strict";var e=n(require("express")),t=require("react-router-dom"),r=n(require("fs")),s=n(require("../src/App")),i=require("react-dom/server"),u=require("react/jsx-runtime");function n(e){return e&&e.__esModule?e:{default:e}}const o=process.env.PORT||3e3,d=r.default.readFileSync("dist/index.html").toString(),l=d.split("Loading..."),a=(0,e.default)();a.use("/dist",e.default.static("dist")),a.use((e,r)=>{const n={},o=(0,u.jsx)(t.StaticRouter,{url:e.url,context:n,children:(0,u.jsx)(s.default,{})});r.status(n.statusCode||200),r.send(`${l[0]}${(0,i.renderToString)(o)}${l[1]}`),r.end()}),console.log(`Listening on http://localhost:${o}`),a.listen(o);
},{"../src/App":"eBcb"}]},{},["Focm"], null)
//# sourceMappingURL=/index.js.map